workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

pipeline:
  tests:
    image: golang:1.10.2
    secrets:
      - my_fake_secret
    commands:
      - make test
      - make static
      - make static
    when:
      event: [pull_request, push, tag]

  build:
    image: docker:17.09.0-ce
    commands:
      - docker build -t build .
    when:
      event: [push, tag]

