workspace:
  base: /go
  path: src/github.com/UKHomeOffice/policy-admission

pipeline:
  tests:
    image: golang:1.10.2
    commands:
      - make test
      - make static
      - make static
    when:
      event: [pull_request, push, tag]

